DECLARE @VarTable TABLE
(
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    NAME VARCHAR(20),
    EMAIL VARCHAR(20),
    AGE INT,
    SALARY DECIMAL(10,2)
);

INSERT INTO @VarTable (NAME, EMAIL, AGE, SALARY)
SELECT NAME, EMAIL, AGE, SALARY
FROM Employee;

SELECT * FROM @VarTable;
SELECT * FROM Employee